### ISSUE TITLE
ScrollablePositionedList example file not found

### ISSUE THREAD

**Issue by RomanKornev** [google/flutter.widgets#190]
## Problem description
Example has incorrect link to a file

## Steps to reproduce
1. Go to https://pub.dev/packages/scrollable_positioned_list/example
2. Click on example file
3. 404 Not found https://github.com/google/flutter.widgets/blob/master/example/lib/scrollable_positioned_list_example.dart

**Comment by jamesderlin** [comment]
I think that this is a problem with pub.dev (https://pub.dev/packages/file/example and https://pub.dev/packages/visibility_detector/example hae the same problem) for GitHub repositories that are home to multiple packages.  The example page is automatically generated, and it seems unlikely that this is a configuration issue with the package since pub.dev shows the correct example content.

**Comment by jamesderlin** [comment]
I take that back.  The content comes from the package uploaded to `pub.dev`.  I suppose that the package configuration should point to its subdirectory in the GitHub repository rather than to the repository root.
