### ISSUE TITLE
"initialScrollIndex" in "scrollable_positioned_list" does nothing

### ISSUE THREAD

**Issue by eliranwong** [google/flutter.widgets#212]
## Problem description
I am writing about "scrollable_positioned_list" a/v at https://pub.dev/packages/scrollable_positioned_list.  I found this package useful, but "initialScrollIndex" does not work.

## Steps to reproduce

I added a widget, returning "ScrollablePositionedList.builder ...", in which I specified "initialScrollIndex".  However, it does not work.  The list does not scroll to the initial index automatically.  After the list is loaded, I need to call jumpTo function to scroll the list instead.  I expect when "initialScrollIndex" is specified, the list automatically scrolled to the right position after it is loaded.

  Widget _buildVerses(BuildContext context) {
    scrollController = ItemScrollController();
    itemPositionsListener = ItemPositionsListener.create();
    
    return ScrollablePositionedList.builder(
      padding: EdgeInsets.zero,
      itemCount: _data.length,
      itemBuilder: (context, i) => _buildVerseRow(context, i),
      initialScrollIndex: _scrollIndex,
      initialAlignment: 0.0,
      itemScrollController: scrollController,
      itemPositionsListener: itemPositionsListener,
    );
  }

## Expected behavior
I expect when "initialScrollIndex" is specified, the list automatically scrolled to the right position after it is loaded.

## Actual behavior
The list does not scroll according to initialScrollIndex

## Environment
Testing in Android and iOS

## Additional details
n/a

**Comment by xsahil03x** [comment]
The widget uses the `initialScrollIndex` & `initialAlignment` only on the first build. If you want to rebuild the list whenever the index changes, you can set a key `ValueKey(initialIndex + initialAlignment)`

**Comment by banderberg** [comment]
@xsahil03x What if I want it to rebuild the list even when the index does not change?  In my case, each widget contains a list of items that can be added to (or removed).  So, if (via another screen widget) I add an item to the widget at index 10, when I Navigate.pop back to the screen with my list of widgets, I want my list to scroll to index 10 again.  But, since the initial scroll index is still 10, I am stuck at the top of my list and have to scroll down manually.
