### ISSUE TITLE
ScrollablePositionedList should be bounce when jumping to the end of the list

### ISSUE THREAD

**Issue by rockingdice** [google/flutter.widgets#23]
Now it's stopped at the jumping position and will not trigger the physical reaction.

**Comment by tarobins** [comment]
So the problem seems to be that here

https://github.com/flutter/flutter/blob/652be88ecd259407b47d0dbeb243f5fbbef81638/packages/flutter/lib/src/rendering/viewport.dart#L1279

the maxScrollExtent as passed to the ViewportOffset is bounded below by 0.  However, in the case of jumping to the last item in the list, I create a CustomScrollView such that the item is the centered Sliver in a custom scrollview, and so at a scroll offset of 0, the item is at the top of the viewport with some empty space below.   If we wanted that item to then go back to the bottom of the viewport when it is jumped to, and stay there as the user tries to scrolls, we could have ViewportOffset's maxScrollExtent to go negative.  

I replaced the above line with

math.max(math.min(0.0, _minScrollExtent + mainAxisExtent * anchor), _maxScrollExtent - mainAxisExtent * (1.0 - anchor))

and that made the sample app (modified so you could jump to the last item) work as described in this bug when I jumped to the bottom of the list, or if I tried to manually scroll past the end of the list after the jump.  

Making this change causes a problem however, because then if one wants to center an item somewhere above the bottom of the viewport with empty space below it, they can't.  And, in fact, this test https://github.com/flutter/flutter/blob/0df1594ba263493937e3e4d5d2c5062a7ecc6c71/packages/flutter/test/widgets/custom_scroll_view_test.dart#L27 fails with that change (it is the only test in the flutter test suite that fails with that change).  I suspect we don't want to make that change.

I was thinking it might be more flexible if the max and min calculations done here 

https://github.com/flutter/flutter/blob/652be88ecd259407b47d0dbeb243f5fbbef81638/packages/flutter/lib/src/rendering/viewport.dart#L1279

were instead done inside the ViewportOffset because then we could supply the viewport with an ViewportOffset that did allow negative maxScrollExtents in the cases were we want to allow such things.  It actually does make me wonder why the Viewport is making the decision about the bounding of the max and min scroll offsets rather than the ViewportOffset?  

Would it at all make sense to move those calculations to the ViewportOffset and its subclasses?  Obviously some API changes would be needed to pass the needed information.  

An alternative for the ScrollablePositionedList would be to have a custom RenderViewport that overrides performLayout that modifies that min and max.  That solution will mean a bunch of custom classes so the custom RenderViewport can be used and some duplicate code in its perform layout.  

@goderbauer do you have any opinion or know anyone who might?

**Comment by rockingdice** [comment]
Thank you for the details! 
Is that possible to try to calculate the position of the jumping item after bouncing? I think it's better because the users won't need to see the bouncing animation. 
The bouncing is to warn the users, they cannot drag the list further, the list is at the end and cannot move on. 
But for jumping, it's not a consistent behavior and should be finished immediately.
So I think if it's jumping to the last position it should be, this issue can also be solved without making more changes to the lower layer codes.

**Comment by tarobins** [comment]
Getting the bounds correct for the ScrollPosition is also important to prevent the user from over scrolling.  I have an, at least temporary solution, I just need to implement it.   I'll try to do that next week.

**Comment by rockingdice** [comment]
@tarobins  Looking forward to it!

**Comment by tarobins** [comment]
I've submitted a fix to google's internal code repo.  It'll take a few days to filter through to here and then I'll close the bug.

**Comment by tarobins** [comment]
I've written a doc that proposes a solution to a few other bugs that might have an effect on the behaviour of the solution to this bug.  If you are interested, please take a look and leave comments.

https://docs.google.com/document/d/1ozIndwAbYcd96ktOX8LnsZ1L-K08q2XvdDD3G_ruEE8/edit#

**Comment by yungzhu** [comment]
Sorry, I want to know if this problem is solved in the end, which is very important to us,thanks

**Comment by tarobins** [comment]
@yungzhu  So, I think the exception is fixed.  Is there a specific problem you're running in to?

**Comment by yungzhu** [comment]
> @yungzhu So, I think the exception is fixed. Is there a specific problem you're running in to?

I'm using the latest version and it still bounces when I locate the bottom!

**Comment by alicehyxx** [comment]
this problem is still exist..
