### ISSUE TITLE
VisibilityDetector VisibilityFraction no longer 0 when new route slides on top

### ISSUE THREAD

**Issue by lifenautjoe** [google/flutter.widgets#29]
After upgrading to flutter_widgets: 0.1.6 to make it compatible with latest Flutter release, when sliding a route on top of the route with the visibility widget, is now still considered visible with fractions of ~ `0.8601489100280483`, while in reality, should be zero.

When switching tabs or opening a root route, visible fraction is set to 0 as expected.

The route I'm pushing on top of the element is custom

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class OBSlideRightRoute<T> extends PageRouteBuilder<T> {
  final Widget widget;
  final Key key;

  OBSlideRightRoute({this.widget, this.key})
      : super(
            opaque: false,
            transitionDuration: const Duration(milliseconds: 200),
            pageBuilder: (BuildContext context, Animation<double> animation,
                Animation<double> secondaryAnimation) {
              return Dismissible(
                  background: const DecoratedBox(decoration: const BoxDecoration(
                      color: Color.fromARGB(0, 0, 0, 0)
                  ),),
                  direction: DismissDirection.startToEnd,
                  onDismissed: (direction) {
                    Navigator.pop(context);
                  },
                  key: key,
                  child: Material(
                    child: widget,
                  ));
            },
            transitionsBuilder: (BuildContext context,
                Animation<double> animation,
                Animation<double> secondaryAnimation,
                Widget child) {
              return SlideTransition(
                  position: new Tween<Offset>(
                    begin: const Offset(1.0, 0.0),
                    end: Offset.zero,
                  ).animate(
                      CurvedAnimation(parent: animation, curve: Curves.fastOutSlowIn)),
                  child: child);
            });
}
```

**Comment by jamesderlin** [comment]
> I haven't looked into the code of the VisibilityDetector but I imagined if anything is on the way, be it a stacked element or a route with opaque: false but covering it (for example a bottomsheet), it would also report back correct visibility ratios.

`VisibilityDetector` basically works by determining how much of it is rendered.  If something is on top of the `VisibilityDetector` and is obscuring it, then visibility *should* be correctly reported.  However, I *think* `opaque: false` (and anything else involving transparency) undermines that by still rendering the `VisibilityDetector`.  Since the `VisibilityDetector`'s widget bounds are still onscreen, it still reports itself as being almost completely visible. (It's not 100% visible probably because of widgets on top.  If your new route had some background widget that covered the entire screen, I'm guessing that would help.)

> Yes, opaque: true is exactly what I want, however that also adds a white barrier behind, which defeats the Slidable route design.

Is `barrierColor` `null`?  The behavior you're observing isn't what I'd expect from my cursory look at the documentation, and using `opaque: false` seems like a workaround that you shouldn't be forced to use.  That possibly is an issue with `PageRouteBuilder`; I'll have to check with my colleagues who are more familiar with it. (Again, sample code reproducing the problem would speed things up a lot.)

**Comment by lifenautjoe** [comment]
With `opaque: false` and barrierColor null, still shows that grey backdrop. If I pass `barrierColor: Colors.transparent` it fails on an assertion that barrierColor can't be transparent.

If I pass `barrierColor: Colors.fromRgba(0,0,0,3)` I see the black barrier overlay on top of that grey layer you see in my GIF.

I'll set some time up in the weekend to make a demo repo.

**Comment by jamesderlin** [comment]
Were you ever able to create a sample code to reproduce the problem?

**Comment by jamesderlin** [comment]
I don't think that there's going to be anything that I can do about this. `VisibilityDetector` fundamentally works by determining how much of its bounding box is clipped.  I don't think that there's any reasonable way to reconcile this with opacity effects.  I will add a "Known limitations" section to the `README.md` file and note this.
