### ISSUE TITLE
visibility_detector 0.3.3 released but it depends on Flutter SDK version >=2.12.0...

### ISSUE THREAD

**Issue by hicnar** [google/flutter.widgets#366]
...and the most recently released stable Flutter SDK is  2.10.5.
Shouldn't packages released to pub.dev be compatible with the latest stable framework release?

![Screenshot 2022-05-07 at 09 20 27](https://user-images.githubusercontent.com/1816194/167245832-94cec3d9-8e6f-432f-933c-6ac071226839.png)

**Comment by pradeepsthapa** [comment]
Same problem
scrollable_positioned_list >=0.3.2 which requires Flutter SDK version >=2.12.0, version solving failed.

**Comment by jamesderlin** [comment]
>  Shouldn't packages released to pub.dev be compatible with the latest stable framework release?

Yeah, there probably should be a formal policy of publishing a non`-dev` version only if tests pass against stable dependencies.  It shouldn't be strictly necessary since as long as the package's version dependencies are correct and as long as your own `pubspec.yaml` doesn't force using an incompatible version, `pub` should automatically pick a version that satisfies version constraints.  That is, you should get a problem like:

>  scrollable_positioned_list >=0.3.2 which requires Flutter SDK version >=2.12.0, version solving failed.

only if your `pubspec.yaml` requires `scrollable_positioned_list` to have a minimum version of 0.3.2.

That said, the version constraints for these packages was broken and, if the broken package isn't retracted, would require setting a *maximum* package version to avoid broken versions, which also is undesirable. 

CC @xster

**Comment by 2e2ee95304418f96** [comment]
Same problem , the doc should say which  versioncode support the latest flutter stable version.

**Comment by priyankabambharoliya-official** [comment]
I am getting this in the `0.3.2` version

```
The current Flutter SDK version is 2.10.4.

Because dltcapital depends on scrollable_positioned_list >=0.3.1 which requires Flutter SDK version >=2.10.5, version solving failed.
pub get failed (1; Because dltcapital depends on scrollable_positioned_list >=0.3.1 which requires Flutter SDK version >=2.10.5, version solving failed.)
```

**Comment by jamesderlin** [comment]
> Same problem , the doc should say which versioncode support the latest flutter stable version.

If you read the [visibility_detector's changelog](https://pub.dev/packages/visibility_detector/changelog), you'll see that 0.3.2 and 0.3.3 tried to correct versioning problems introduced by 0.3.0.  If you want a version compatible with Flutter 2.10.5, use the version prior to 0.3.0: 0.2.2.

Same thing applies to [scrollable_positioned_list's changelog](https://pub.dev/packages/scrollable_positioned_list/changelog).  The version of scrollable_positioned_list prior to the versioning snafu was 0.2.3.

But, as of writing, the latest stable version of Flutter is now 3.0.
