### ISSUE TITLE
ScrollablePositionedList rebuild a deleted list item

### ISSUE THREAD

**Issue by antoinefBam** [google/flutter.widgets#37]
Hello,

I am using a `ScrollablePositionedList` coupled with a `ChangeNotifierProvider`.
I want to give the user the possibility to delete an item of the list.

- The user click on the delete button associated to an item.
- Then provider is called and remove this item from the model.
- Then `notifyListeners()` is called.
- `ScrollablePositionedList` is rebuild with the updated list of item.

For some reasons, the widget associated to the deleted item is also rebuild, which causes an error.

For now, if it occurs, I return an empty container but it is only a quick fix.

I'm pretty sure the problem comes from `ScrollablePositionedList` because everything works fine with a `ListView`.

Here is a minimal example to reproduce the problem:

```
import 'package:flutter/material.dart';
import 'package:flutter_widgets/flutter_widgets.dart';
import 'package:provider/provider.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider<MyModel>(
      builder: (context) => MyModel(),
      child: MaterialApp(
        home: Scaffold(
          appBar: AppBar(title: const Text('My App')),
          body: Container(
            padding: const EdgeInsets.only(left: 16.0),
            width: 200,
            child: Consumer<MyModel>(
              builder: (context, myModel, child) {
                print('Build ScrollablePositionedList');
                print('itemIDs: ${myModel.itemIDs}');
                print('itemsMap: ${myModel.itemsMap}');
                return ScrollablePositionedList.builder(
                  scrollDirection: Axis.vertical,
                  itemCount: myModel.itemIDs.length,
                  itemBuilder: (BuildContext context, int index) {
                    final itemID = myModel.itemIDs[index];
                    return CustomItem(
                      key: Key('customItem_$itemID'),
                      itemID: itemID,
                    );
                  },
                );
              },
            ),
          ),
        ),
      ),
    );
  }
}

class CustomItem extends StatelessWidget {
  const CustomItem({
    Key key,
    this.itemID,
  }) : super(key: key);

  final String itemID;

  @override
  Widget build(BuildContext context) {
    final myModel = Provider.of<MyModel>(context);
    print('Build CustomItem $itemID');

    // DEBUG ********
    if (myModel.itemsMap[itemID] == null) {
      print('Building a deleted item...');
      return Container(
        width: 0.0,
        height: 0.0,
      );
    }
    // **************

    return Row(
      children: <Widget>[
        Text(myModel.itemsMap[itemID]['label']),
        IconButton(
          icon: Icon(Icons.delete),
          disabledColor: Colors.grey,
          onPressed: myModel.itemIDs.length > 1 ? () => myModel.removeItem(itemID) : null,
        )
      ],
    );
  }
}

class MyModel with ChangeNotifier {
  List<String> itemIDs = ['A', 'B', 'C'];
  Map<String, Map<String, dynamic>> itemsMap = {
    'A': {
      'label': 'Item A',
    },
    'B': {
      'label': 'Item B',
    },
    'C': {
      'label': 'Item C',
    },
  };

  void removeItem(itemID) {
    print('Remove item $itemID');
    final itemIndex = itemIDs.indexWhere((id) => id == itemID);
    if (itemIndex > -1) {
      itemIDs.removeAt(itemIndex);
      itemsMap.remove(itemID);
    }

    notifyListeners();
  }
}
```

**Comment by tarobins** [comment]
I don't think this is a bug with ScrollablePositionedList.

When you call   `final myModel = Provider.of<MyModel>(context);` you tell the framework to update rebuild the widget's context whenever the model is updated (more precisely when notifyListeners is called).  When the item is removed, all the contexts 'listening' to that model get updated, even if those contexts might be removed at some point in the rebuild process.  

Flutter does mark some elements as inactive shortcuts the rebuild process for inactive elements (eg. here https://github.com/flutter/flutter/blob/1e50db60ad7df6879b3633671c7eb05160afd4f1/packages/flutter/lib/src/widgets/framework.dart#L3923) and that happens when ListView is used.  When ScrollablePositionedList is used, the CustomItem for the deleted item, which is listening to the model, gets rebuilt before it gets marked as inactive, so it tries to access the deleted item.  I'm not sure why rebuilding and marking inactive happens in a different order when using ScrollablePositionedList, but both seem like valid orders of events to me; however, I'm still open to being convinced that ScrollablePositionedList is doing something wrong and not allowing elements to be marked as inactive when they should be.  

I think you can fix this immediate problem with changing the line in CustomItem.build to 

`final myModel = Provider.of<MyModel>(context, listen: false);`

so each individual item is not listening for updates.

I was a little surprised that still worked, but I think it's because Consumer.build is calling Provider.of (https://github.com/rrousselGit/provider/blob/00d0f8f8020dcfe876bd7826f176e1ca2feeaac7/packages/provider/lib/src/consumer.dart#L182), so the whole tree under Consumer is listening for updates.  

Let me know if you run into other trouble with updates once you do that.

**Comment by antoinefBam** [comment]
Thanks a lot for your quick reply and the better understanding of the events happening during the scenario.
Setting up the listener to false is ok for me now.
