### ISSUE TITLE
Auto scroll is issue ?

### ISSUE THREAD

**Issue by harryandroiddev** [google/flutter.widgets#456]
for auto scrolling to the end of the list i have used :

`var index = list.length - 1;
                itemScrollController.scrollTo(
                    index: index, duration: Duration(seconds: 10));`

for small no. of list items , it works fine , but when the list size grows like 20 to 50 items it just skips the items and jumps to the last elements of the items . how it is possible to scroll through all the items without skipping anyone.

**Comment by tarobins** [comment]
The skipping is intentional.  If the list is long, scrolling though the whole list would be very slow, so we actually create an illusion of scrolling by blending two lists, one close to the initial position and once close the target.  

If you want to scroll through all the items, you will need to check what item is near the bottom of the widget, scroll to that item, then repeat until you're at the end of the list.
