### ISSUE TITLE
(ScrollablePositionedList) When alignment is 0, and I want to scroll to the last few items in list,it will have bounce effect

### ISSUE THREAD

**Issue by luckysmg** [google/flutter.widgets#71]
As the title describes, I hope  that it has bounce effect when using my finger ,but when using ItemScrollController to scroll to bottom and aligment is 0, i dont want it has this effect......

**Comment by marcglasberg** [comment]
For example, if you jump the first item to the center of the viewport, it will "bounce back" to its resting position at the top. Instead, the jump should put it directly into its final resting position at the top.

Even this bouncing back is not working fine. It seems to bounce twice, in a weird motion.

**Comment by marcglasberg** [comment]
I think this issue is related to this: https://github.com/google/flutter.widgets/issues/38

If some jump/alignment overshoots the list, bouncing back is not the correct behavior. This bounces will always seem to be "random". The list should just jump to the limit, already in a resting position.

**Comment by tarobins** [comment]
k.  thinking about this one #38 and some bounciness related to https://github.com/google/flutter.widgets/pull/89

**Comment by tarobins** [comment]
I've written a doc that proposes a solution to this bug and a few other.  If you are interested in the solution to this bug, please take a look and leave comments.

https://docs.google.com/document/d/1ozIndwAbYcd96ktOX8LnsZ1L-K08q2XvdDD3G_ruEE8/edit#

**Comment by marcglasberg** [comment]
@tarobins Added my comments there already.

**Comment by Flucadetena** [comment]
I was having the same issue, I've lost multiple hours with this. It was event creating other strange issues. I solve it by reversing the list and jumping to the first item `index = 0`. That stopped the bouncing and all the other errors. Although this should not be happening, at least it is a solution ;)

**Comment by FakenMaster** [comment]
How did you solve that? Can you show some code? @Flucadetena

**Comment by Flucadetena** [comment]
Hi @FakenMaster of course!! It is very simple. You simple set the `reverse` param in `ScrollablePositionedList.builder` too true. Then when you want to scroll to the last item, you call `controller.jumpTo(index: 0);` Here I live you all the code. If you have any more questions let me know.

`
class ScrollList extends StatefulWidget {
  const ScrollList({Key key}) : super(key: key);

  @override
  _ScrollListState createState() => _ScrollListState();
}

class _ScrollListState extends State<ScrollList> {
  final ItemScrollController _itemScrollController = ItemScrollController();
  List<String> list = ['item_1', 'item_2', 'item_3','item_4', 'item_5', 'item_6','item_7', 'item_8', 'item_9'];

  @override
  void initState() {
    super.initState();
    Timer(Duration(seconds: 3), () => _itemScrollController.jumpTo(index: 0));
  }

  @override
  Widget build(BuildContext context) {
    return ScrollablePositionedList.builder(
      itemScrollController: _itemScrollController,
      itemCount: list.length,
      reverse: true,
      itemBuilder: (context, idx) => Container(
        height: 150,
        width: MediaQuery.of(context).size.width,
        padding: const EdgeInsets.symmetric(horizontal: 16),
        color: Colors.blue,
      ),
    );
  }
}
`




**BTW I've had some problems when calling `controller.animateTo()` when I have multiple scrolls/listView/etc with the same controller. If this is your case, if you have the `ScrollableList` inside a `CustomScrollView` or the like, simple call `controller.jumpTo()` instead of `controller.animateTo()`.

**Comment by marcglasberg** [comment]
Reversing the list is not a fix. It's a workaround than not everybody can use and doesn't solve all the undue bouncing. This must be properly fixed as discussed in https://docs.google.com/document/d/1ozIndwAbYcd96ktOX8LnsZ1L-K08q2XvdDD3G_ruEE8/edit#

**Comment by Ciock** [comment]
Try `physics: ClampingScrollPhysics()` in ScrollablePositionedList()

from docs:

> Scroll physics for environments that prevent the scroll offset from reaching
> beyond the bounds of the content.
